# Note: Terraform cloud-init automatically deploys both frontend and backend
# Frontend: Built and served via nginx on port 80
# Backend: Runs as systemd service on port 3000
# ============================================================================

# STEP 1: Get IPs from Terraform outputs (run in your local terminal)
# ============================================================================
# Get Load Balancer Public IP (this is the frontend IP users will access)

# Get Frontend VM Public IPs (for SSH connection)

# Get Backend Instance Pool ID

# Save these values:
# LB_PUBLIC_IP=<load_balancer_public_ip>
# FRONTEND_VM_IP=<first_frontend_public_ip>
# BACKEND_POOL_ID=<backend_instance_pool_id>

# STEP 2: Verify Deployment Status
# ============================================================================
# Check if services are accessible via Load Balancer
curl http://LB_PUBLIC_IP
curl http://LB_PUBLIC_IP:3000/api/health

# STEP 3: Access Frontend VM for Troubleshooting (if needed)
# ============================================================================
# Copy SSH keys to Frontend VM (run from your local laptop)
# Replace YOUR_KEY_PATH with your SSH private key path (e.g., ~/.ssh/id_rsa)
# Replace FRONTEND_VM_IP with the IP from step 1
scp -i ~/.ssh/YOUR_KEY ~/.ssh/YOUR_KEY opc@FRONTEND_VM_IP:~/.ssh/
scp -i ~/.ssh/YOUR_KEY ~/.ssh/YOUR_KEY.pub opc@FRONTEND_VM_IP:~/.ssh/

# Connect to Frontend VM
ssh -i ~/.ssh/YOUR_KEY opc@FRONTEND_VM_IP

# Once connected to Frontend VM, run the following commands:

# Check nginx status
sudo systemctl status nginx

# Check if frontend files are deployed
ls -la /usr/share/nginx/html/

# View nginx logs
sudo tail -f /var/log/nginx/access.log
sudo tail -f /var/log/nginx/error.log

# Check cloud-init logs (to see if deployment completed)
sudo cat /var/log/cloud-init-output.log

# Restart nginx if needed
sudo systemctl restart nginx

# STEP 4: Access Backend Instance Pool Instances (via Frontend VM)
# ============================================================================
# From Frontend VM, get backend instance private IPs using OCI CLI
# First, install OCI CLI if not already installed:
# bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)"

# List backend instances in the pool
oci compute-management instance-pool list-instances --instance-pool-id BACKEND_POOL_ID --compartment-id YOUR_COMPARTMENT_ID

# Get private IP of a backend instance (use the output from above command)
# Then SSH to backend instance from Frontend VM:
ssh -i ~/.ssh/YOUR_KEY opc@BACKEND_INSTANCE_PRIVATE_IP

# Once connected to Backend VM, run the following commands:

# Check backend service status
sudo systemctl status bharatmart-backend

# View backend service logs
sudo journalctl -u bharatmart-backend -f

# Check if backend is running
ps aux | grep node

# Check backend port
sudo netstat -tlnp | grep 3000

# Restart backend service if needed
sudo systemctl restart bharatmart-backend

# View cloud-init logs
sudo cat /var/log/cloud-init-output.log

# Check .env file (auto-generated by Terraform)
cat /opt/bharatmart/.env

# STEP 5: Manual Deployment (if cloud-init failed or needs update)
# ============================================================================
# If you need to manually deploy or update, follow these steps:

# On Frontend VM:
cd /opt/bharatmart
git pull
npm install
npm run build
sudo rm -rf /usr/share/nginx/html/*
sudo cp -r dist/* /usr/share/nginx/html/
sudo systemctl restart nginx

# On Backend VM (access via Frontend VM):
cd /opt/bharatmart
git pull
npm install
npm run build:server
sudo systemctl restart bharatmart-backend

# STEP 6: View Application Logs
# ============================================================================
# Backend logs (on Backend VM):
sudo journalctl -u bharatmart-backend -n 100
sudo journalctl -u bharatmart-backend -f

# Frontend nginx logs (on Frontend VM):
sudo tail -f /var/log/nginx/access.log
sudo tail -f /var/log/nginx/error.log

# Application logs (if configured):
tail -f /opt/bharatmart/logs/api.log

# STEP 7: Check Load Balancer Health
# ============================================================================
# From your local terminal, check backend health:
curl http://LB_PUBLIC_IP:3000/api/health

# Check frontend:
curl http://LB_PUBLIC_IP

# ============================================================================
# Access URLs (use Load Balancer Public IP from step 1):
# ============================================================================
# Frontend: http://LB_PUBLIC_IP
# Backend API: http://LB_PUBLIC_IP:3000/api
# Backend Health Check: http://LB_PUBLIC_IP:3000/api/health
